# Generated by Django 3.0.2 on 2020-01-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatinho', '0005_auto_20200113_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatinho',
            name='cor',
            field=models.CharField(choices=[('PRETO', 'Preto'), ('BRANCO', 'Branco'), ('PARDO', 'Pardo'), ('BEGE', 'Bege'), ('TRICOLOR', 'Tricolor'), ('LARANJA', 'Laranja'), ('CINZA', 'Cinza')], max_length=100),
        ),
    ]
